const double GRAVITY = -10;

//paths
const String PATH_ARCTIC_LEVEL_BG = "artic level final 2.png",
    PATH_MAIN_MENU_BG = "MainMenu.png",
    PATH_LOGO_APP = "assets/images/logoapp.png",
    PATH_LOGO_MAIN = "assets/images/logomain.png",
    PATH_BUTTON_MOTION_LEFT = "assets/images/sprites/button/left button.png",
    PATH_BUTTON_MOTION_RIGHT = "assets/images/sprites/button/right button.png",
    PATH_BUTTON_MOTION_UP = "assets/images/sprites/button/up button.png",
    PATH_BUTTON_MAIN_MENU =
        "assets/images/sprites/main menu buttons/main menu button.png",
    PATH_BUTTON_PICKUP = "assets/images/sprites/button/pick up button.png",
    PATH_WILDFIRE_BG = "wildfire aussie.png",
    PATH_PLAYER_LEFT = "sprites/main_char/left/",
    PATH_PLAYER_RIGHT = "sprites/main_char/right/",
    PATH_POLAR_BEAR_LEFT = "sprites/Polar Bear/left/",
    PATH_POLAR_BEAR_RIGHT = "sprites/Polar Bear/right/",
    PATH_IGLOO_LEFT = "assets/images/sprites/igloo/igloo.png",
    PATH_IGLOO_RIGHT = "assets/images/sprites/igloo/igloo2.png",
    PATH_ARCTIC_TILE = "assets/images/sprites/arctic_level/tiles/ice_tiles.png",
    PATH_SETTINGS_TILE = "assets/images/setting page.png",
    PATH_SETTINGS_BUTTON = "assets/images/Rectangle 220.png",
    PATH_NOTO_FIRE = "assets/images/noto_fire.png",
    PATH_SOUND = "assets/images/sound.png",
    PATH_SETTINGS_BORDER = "assets/images/Rectangle 15.png",
    PATH_BUTTON_POLAR = "assets/images/sprites/button/return to main menu.png",
    PATH_SOUND_PICK = "pick.ogg",
    PATH_SOUND_JUMP = "jump.ogg",
    PATH_SOUND_DROP = "drop.ogg";
